/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tarea5;



import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;
import java.lang.reflect.Array;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FrmRegistrar extends javax.swing.JFrame {
private static Scanner sc;
private static int intentos;
private String user, pw;
String ima;
funcioness fun = new funcioness();

    /**
     * Creates new form FrmMenu
     */
public void limpiardatos()
{
    this.users.setText("");
      this.correo.setText("");
        this.pass.setText("");
          this.pass2.setText("");
}

public FrmRegistrar() {
        initComponents();
       this.setLocationRelativeTo(null);
               funcioness.CargarLogo(logo);
          funcioness.nombreU(u);
        limpiardatos();
        
    }

    public static void setIntentos(int intentos) {
        FrmRegistrar.intentos = intentos;
    }
public void imagen(){
        Path origenPath = FileSystems.getDefault().getPath(ima);
        ima =System.getProperty("user.home") +"\\Documents\\" +correo.getText()+".jpg"; 
        
        Path destinoPath = FileSystems.getDefault().getPath(ima);

        try {
            Files.move(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            System.err.println(e);
        }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        users = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        u = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 145, -1));

        jLabel1.setText("usuario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        jPanel1.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 145, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        jPanel1.add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 145, -1));

        correo.setText(" ");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 145, -1));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel5.setText("Seleccione el avartar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jButton3.setText("Seleccione su avatar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));
        jPanel1.add(avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 119, -1, -1));
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 101, 130, 80));

        logo.setText("jLabel6");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 60, 60));
        jPanel1.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
        JFileChooser fileChooser = new JFileChooser();
        int a = fileChooser.showOpenDialog(null);

        if (a == JFileChooser.APPROVE_OPTION) {

            System.out.println(fileChooser.getSelectedFile().getAbsolutePath());
            fun.Regima(img,fileChooser.getSelectedFile().getAbsolutePath() );
            ima= fileChooser.getSelectedFile().getAbsolutePath();
        }
    }//GEN-LAST:event_jButton3ActionPerformed
        public String convertirAMurcielago(String cadena)
    {
        cadena = cadena.replace('m', '0');
        cadena = cadena.replace('u', '1');
        cadena = cadena.replace('r', '2');
        cadena = cadena.replace('c', '3');
        cadena = cadena.replace('i', '4');
        cadena = cadena.replace('e', '5');
        cadena = cadena.replace('l', '6');
        cadena = cadena.replace('a', '7');
        cadena = cadena.replace('g', '8');
        cadena = cadena.replace('o', '9');
        
        return cadena;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{

            Path Pathusuario = Paths.get("./src/base/base.txt");
            System.out.println("usuario"+ Pathusuario.toAbsolutePath());
            String p1 = pass.getText();
            String p2 = pass2.getText();
            imagen();
            if(!p1.equals(p2)){
                JOptionPane.showMessageDialog(null, "Contraeñas distintas");
            }
            else{
  
  
//File f = new File(Pathusuario.toUri());    
//FileWriter fw = new FileWriter(Pathusuario.toString(), true);

String cadena ="";
cadena +=this.users.getText() + ", ";
cadena +=this.correo.getText() + ", ";
cadena +=String.valueOf(this.pass.getPassword()) + ", " ;
cadena +=String.valueOf(this.pass2.getPassword()) +  ", ";
cadena +=ima + System.lineSeparator();
       System.out.println("cadena: " + cadena);
       Files.write(Pathusuario,cadena.getBytes(), StandardOpenOption.APPEND); 


  


   //JOptionPane.showMessageDialog(null, "Archivo creado Exitosamente en : "+ Pathusuario.toString());

      Path murcielago = Paths.get("./src/base/murcielago.txt");
    
            String cadenaInsertMurcielago = "1, ";
            cadenaInsertMurcielago += convertirAMurcielago(this.users.getText()) + ", ";
            cadenaInsertMurcielago += convertirAMurcielago(this.correo.getText()) + ", ";
            cadenaInsertMurcielago += convertirAMurcielago(String.valueOf(this.pass.getPassword())) + System.lineSeparator();
            cadenaInsertMurcielago +=ima + System.lineSeparator();
            Files.write(murcielago , cadenaInsertMurcielago.getBytes() , StandardOpenOption.APPEND);        
     //JOptionPane.showMessageDialog(null, "Archivo creado Exitosamente en : "+murcielago.toString());

    
      }  
        }
        catch(Exception e)
        {

            JOptionPane.showMessageDialog(null, "ERROR: "+ e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmMenu menu= new  FrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JLabel u;
    private javax.swing.JTextField users;
    // End of variables declaration//GEN-END:variables
}
